### PR TITLE
Swift bulk delete

### PR DESCRIPTION
**Pull request by hgw77**

### CODE REVIEW

**Comment by gildub** [comment]
@hgw77, that's a very straight forward way of adding the feature, unfortunately we cannot hack the Openstack's project libraries directly. The reason is because those files are going to be moved outside of Misty and will be be source from an independent repo and ultimately directly from Openstack project source code. The place to add features would be `lib/misty/openstack/swift/v1.rb`.

Also wrapper projects could always add feature directly on the Openstack Schema, I would not recommend it for maintenance reason.

**Comment by gildub** [comment]
@hgw77, https://github.com/flystack/misty/pull/92 is more what I meant.

**Comment by hgw77** [comment]
ah ok, #92 is more user convenient 👍

**Comment by gildub** [comment]
@hgw77, ok cool, I wasn't sure and didn't want to steal the feature from you ;)

**Pull request closed without merging**
