### PR TITLE
reauthenticate if token expired

### PR DESCRIPTION
**Pull request by Carthaca**
replaces https://github.com/flystack/misty/pull/104

### CODE REVIEW

**Comment by Carthaca** [comment]
@andypf can you please have a look at the failing tests? I think it has to be re-recorded

**Comment by andypf** [comment]
@gildub can you please re-record the tests? I do not have the right environment for it.

**Comment by gildub** [comment]
@andypf , sure, I'm on it.

**Comment by gildub** [comment]
The integration test update to be addressed in a separate pull request. Thanks

**Comment by gildub** [comment]
Fixed VCR in https://github.com/flystack/misty/pull/109

**Comment by gildub** [comment]
@andypf ^

**Pull request merged**
