### PR TITLE
Transparent HTTP requests

### PR DESCRIPTION
**Pull request by gildub**
Let's leave the server automatically handle the data format in PUT, POST and PATCH requests.

### CODE REVIEW

**Comment by majewsky** [comment]
I like that this allows for non-JSON bodies, but at the cost of API ergonomics (all these `Misty.to_json()` and the manual `Content-Type` setting). Can we have a middle-ground like so?

1. If `body.is_a?(Hash) || body.is_a?(Array)`, encode as JSON and include `Content-Type: application/json` as in previous versions.
2. Otherwise (i.e. for `body.is_a?(String)` etc.), do as it is right now, i.e. send as-is with no automatic `Content-Type`.

**Comment by gildub** [comment]
@majewsky, 

Do we need any middle ground? As far as my tests went, the API services can detect the data content whether JSON or String or "*/*". Creation (PUT) worked just fine (no Content-Type specified). 

Since Misty is becoming more an more a conduit for Openstack APIs the more transparent it is the better. Other layer (such as flystack/foggy or similar) to take care of the content. Do you have any case where this approach is not working or causing any issues?

**Comment by hgw77** [comment]
The current behavior is that I need to encode any Array or Hash to json when I send a PUT/PATCH or POST to the API, it would be much more convenient if the Array or Hash is automaticly converted to json like the proposal from @majewsky 

about the Content-Type. At the moment I can see the following behavior:

0. I create a misty object without setting the the headers attribute content-type for identity
1.  than I send for instance update project ``misty.identity.update_project(id, Misty::to_json({project: params}))``
2. and the api returns a 400 bad request,

The reason, I see in mitmproxy that the request was send with ``Content-Type: application/x-www-form-urlencoded`` thats the default behavior for [net::http](https://github.com/ruby/ruby/blob/trunk/lib/net/http.rb#L1253) so the only way to fix that behavior is to set the headers attribute ``headers: {'Content-Type' => 'application/json', 'Accept' => 'application/json'}`` when I create the misty object. It would be nice that the content-type is set to ``application/json`` if a json was detected

**Comment by gildub** [comment]
@hgw77, I see what you guys meant, it makes sense, I'm going to look into it. Thanks

**Comment by hgw77** [comment]
any updates on this?

**Comment by gildub** [comment]
@hgw77, yes, just have to make sure it's manageable with the options, I'll look into that.

**Comment by hgw77** [comment]
@gildub thank you, at the moment it breaks most of my PUT/POST/UPDATE actions, so it would be nice we can find a solution to have the old behevior :-)

**Comment by gildub** [comment]
@hgw77, ok I'll take care of that ASAP, sorry got busy with OpenStack Summit down under in Sydney.

**Comment by gildub** [comment]
@majewsky, @hgw77, https://github.com/flystack/misty/pull/91 should have addressed the issue, it seems like we've been back and forth but I think that's good because we now have more flexibility for encoding data and headers. Thank you!

**Pull request merged**
