### PR TITLE
reauthenticate if token expired

### PR DESCRIPTION
**Pull request by andypf**

### CODE REVIEW

**Comment by gildub** [comment]
@andypf, thanks that's a good idea. Could you please remove Neutron file which I think, doesn't belong here. Thanks

**Comment by andypf** [comment]
@Carthaca could you please take a look.

**Comment by Carthaca** [comment]
cherry-picked to https://github.com/flystack/misty/pull/107

**Comment by gildub** [comment]
Closing since it has been replaced by #107.

**Pull request closed without merging**
